# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       hawaii-shell

# >> macros
# << macros

Summary:    Hawaii shell.
Version:    0.2.0.1.20140215.51d1271
Release:    1
Group:      Applications/System
License:    BSD
URL:        https://github.com/mauios/hawaii-shell.git
Source0:    shell-%{version}.tar.bz2
Source100:  hawaii-shell.yaml
Patch0:     Remove-C++11-override.patch
Requires:   qt5-qtdeclarative-import-window2
Requires:   qt5-qtsvg-plugin-imageformat-svg
Requires:   qt5-qttools-qdbus
Requires:   wallpapers
Requires:   fluid
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Compositor)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(liblzma)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5Xdg)
BuildRequires:  pkgconfig(dconf)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(polkit-qt-1)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-server)
BuildRequires:  pkgconfig(pixman-1)
BuildRequires:  pkgconfig(weston)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  qtaccountsservice-devel
BuildRequires:  qtconfiguration-devel
BuildRequires:  cmake
BuildRequires:  qt5-default
BuildRequires:  bzip2-devel
BuildRequires:  greenisland-devel

%description
Provides Hawaii desktop environment shell.

%package devel
Summary:    Devel files for Hawaii
Group:      Development/System
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# Remove-C++11-override.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
cd upstream
%ifnarch %{ix86} x86_64
# HACK!!! Please remove when possible.
# cmake is accelerated but version is too old
mkdir /tmp/bin
cp -a /usr/bin/cmake /usr/share/cmake/Modules /usr/share/cmake/Templates /tmp/bin/
PATH=/tmp/bin:$PATH
/tmp/bin/cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_SKIP_RPATH:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON . -DCMAKE_BUILD_TYPE=RelWithDebInfo
%else
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
%endif

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd upstream
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/hawaii
%{_bindir}/hawaii-shell
%{_libdir}/hawaii/plugins/platformthemes/hawaii.so
%{_libdir}/hawaii/qml/Hawaii/Shell/
%{_libdir}/weston/hawaii-desktop.so
%{_libdir}/libHF1HawaiiShell.so.*
%{_libdir}/weston/hawaii-desktop.so
%{_libexecdir}/starthawaii
%{_libexecdir}/hawaii-shell-client
%{_libexecdir}/hawaii-screensaver
%{_libexecdir}/hawaii-notifications-daemon
%{_datadir}/hawaii/
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/HF1/HawaiiShell/
%{_libdir}/cmake/HF1HawaiiShell/*.cmake
%{_libdir}/libHF1HawaiiShell.so
# >> files devel
# << files devel
